#
# GetKeys.ps1 — Create a Service Principal for Azure Cost Management and populate .env
#
# Prerequisites:
#   - Azure CLI installed (az)
#   - Logged in via: az login
#
# Usage:
#   .\GetKeys.ps1
#
# What it does:
#   1. Creates the .env file if it doesn't exist
#   2. Checks for an existing service principal named "CostManagement-Fabric-SPN"
#   3. Creates the service principal if it doesn't exist
#   4. Assigns "Cost Management Reader" role on the current subscription
#   5. Writes all credentials to the .env file
#

$ErrorActionPreference = "Stop"

# ─── Configuration ────────────────────────────────────────────────────────────
$AppName     = "CostManagement-Fabric-SPN"
$Role        = "Cost Management Reader"
$EnvFile     = Join-Path $PSScriptRoot ".env"
$SecretYears = 2

# ─── Helper functions ─────────────────────────────────────────────────────────
function Write-Info  { param([string]$Message) Write-Host "[INFO] $Message" -ForegroundColor Green }
function Write-Warn  { param([string]$Message) Write-Host "[WARN] $Message" -ForegroundColor Yellow }
function Write-Err   { param([string]$Message) Write-Host "[ERROR] $Message" -ForegroundColor Red }

# ─── Pre-flight checks ───────────────────────────────────────────────────────
$azCmd = Get-Command az -ErrorAction SilentlyContinue
if (-not $azCmd) {
    Write-Err "Azure CLI (az) is not installed. Install from https://aka.ms/install-azure-cli"
    exit 1
}

try {
    $null = az account show 2>$null
    if ($LASTEXITCODE -ne 0) { throw "not logged in" }
} catch {
    Write-Err "Not logged in to Azure CLI. Run 'az login' first."
    exit 1
}

Write-Info "Azure CLI is installed and authenticated."

# ─── Get current subscription info ───────────────────────────────────────────
$accountJson = az account show -o json | ConvertFrom-Json
$SubscriptionId   = $accountJson.id
$SubscriptionName = $accountJson.name
$TenantId         = $accountJson.tenantId

Write-Info "Current subscription: $SubscriptionName ($SubscriptionId)"
Write-Info "Tenant ID: $TenantId"

# ─── Step 1: Create .env file if it doesn't exist ────────────────────────────
if (-not (Test-Path $EnvFile)) {
    Write-Info "Creating $EnvFile file..."
    $timestamp = (Get-Date).ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:ssZ")
    @"
# Azure Cost Management API Configuration
# Auto-generated by GetKeys.ps1 on $timestamp

# Azure Subscription
AZURE_SUBSCRIPTION_ID=
AZURE_SUBSCRIPTION_NAME=

# Azure Tenant
AZURE_TENANT_ID=

# Service Principal credentials
AZURE_CLIENT_ID=
AZURE_CLIENT_SECRET=

# Service Principal display name (for reference)
AZURE_SPN_NAME=

# Ontology display name (optional)
ONTOLOGY_DISPLAY_NAME=CostManagementOntology
"@ | Set-Content -Path $EnvFile -Encoding UTF8
    Write-Info "$EnvFile created."
} else {
    Write-Info "$EnvFile already exists."
}

# ─── Step 2: Check if Service Principal already exists ────────────────────────
Write-Info "Checking for existing service principal '$AppName'..."

$existingApps = az ad app list --display-name $AppName -o json 2>$null | ConvertFrom-Json
$ClientId     = $null
$ClientSecret = $null

if ($existingApps -and $existingApps.Count -gt 0) {
    $ClientId = $existingApps[0].appId
    Write-Info "Service principal '$AppName' already exists (Client ID: $ClientId)."

    Write-Warn "Creating a new client secret (old secrets are not retrievable)..."
    $credJson = az ad app credential reset --id $ClientId --years $SecretYears -o json | ConvertFrom-Json
    $ClientSecret = $credJson.password

    if (-not $ClientSecret) {
        Write-Err "Failed to parse client secret. Check manually."
        exit 1
    }
} else {
    # ─── Step 3: Create the Service Principal ─────────────────────────────────
    Write-Info "Creating service principal '$AppName'..."

    $spJson = az ad sp create-for-rbac --name $AppName --years $SecretYears -o json | ConvertFrom-Json
    $ClientId     = $spJson.appId
    $ClientSecret = $spJson.password

    if (-not $ClientId -or -not $ClientSecret) {
        Write-Err "Failed to parse service principal output. Check manually."
        exit 1
    }

    Write-Info "Service principal created: $ClientId"
}

# ─── Step 4: Assign Cost Management Reader role ──────────────────────────────
Write-Info "Checking role assignment for '$Role' on subscription..."

$scope = "/subscriptions/$SubscriptionId"
$existingRole = az role assignment list --assignee $ClientId --role $Role --scope $scope -o json 2>$null | ConvertFrom-Json

if ($existingRole -and $existingRole.Count -gt 0) {
    Write-Info "Role '$Role' is already assigned."
} else {
    Write-Info "Assigning '$Role' role on subscription $SubscriptionId..."
    az role assignment create --assignee $ClientId --role $Role --scope $scope --output none
    if ($LASTEXITCODE -ne 0) {
        Write-Err "Failed to assign role. You may need Owner or User Access Administrator permissions."
        exit 1
    }
    Write-Info "Role assigned successfully."
}

# ─── Step 5: Update the .env file ────────────────────────────────────────────
Write-Info "Updating $EnvFile with credentials..."

$timestamp = (Get-Date).ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:ssZ")
@"
# Azure Cost Management API Configuration
# Auto-generated by GetKeys.ps1 on $timestamp
# WARNING: This file contains secrets. Do NOT commit to source control.

# Azure Subscription
AZURE_SUBSCRIPTION_ID=$SubscriptionId
AZURE_SUBSCRIPTION_NAME=$SubscriptionName

# Azure Tenant
AZURE_TENANT_ID=$TenantId

# Service Principal credentials
AZURE_CLIENT_ID=$ClientId
AZURE_CLIENT_SECRET=$ClientSecret

# Service Principal display name (for reference)
AZURE_SPN_NAME=$AppName

# Ontology display name (optional — used by 02_create_cost_ontology notebook)
ONTOLOGY_DISPLAY_NAME=CostManagementOntology
"@ | Set-Content -Path $EnvFile -Encoding UTF8

Write-Info "$EnvFile updated successfully."

# ─── Summary ─────────────────────────────────────────────────────────────────
$secretPreview = $ClientSecret.Substring(0, [Math]::Min(8, $ClientSecret.Length)) + "********************************"

Write-Host ""
Write-Host "════════════════════════════════════════════════════════════════" -ForegroundColor Cyan
Write-Host "  Setup Complete" -ForegroundColor Cyan
Write-Host "════════════════════════════════════════════════════════════════" -ForegroundColor Cyan
Write-Host ""
Write-Host "  Subscription:    $SubscriptionName"
Write-Host "  Subscription ID: $SubscriptionId"
Write-Host "  Tenant ID:       $TenantId"
Write-Host "  SPN Name:        $AppName"
Write-Host "  Client ID:       $ClientId"
Write-Host "  Client Secret:   $secretPreview"
Write-Host "  Role:            $Role"
Write-Host "  .env File:       $EnvFile"
Write-Host ""
Write-Host "  Next steps:"
Write-Host "    1. Upload notebooks to your Fabric workspace"
Write-Host "    2. Upload .env to Lakehouse Files (or set env vars)"
Write-Host "    3. Run 01_download_cost_data.ipynb"
Write-Host "    4. Run 02_create_cost_ontology.ipynb"
Write-Host ""
Write-Host "════════════════════════════════════════════════════════════════" -ForegroundColor Cyan
