#
# GetKeys.ps1 -- Create a Service Principal for Azure Cost Management and populate .env
#
# Prerequisites:
#   - Azure CLI installed (az)
#   - Logged in via: az login
#
# Usage:
#   .\GetKeys.ps1                         # SPN + .env only
#   .\GetKeys.ps1 -KeyVaultName "kv-cost"  # Also create Key Vault and store secrets
#
# What it does:
#   1. Creates the .env file if it doesn't exist
#   2. Checks for an existing service principal named "CostManagement-Fabric-SPN"
#   3. Creates the service principal if it doesn't exist
#   4. Assigns "Cost Management Reader" role on the current subscription
#   5. Writes all credentials to the .env file
#   6. (Optional) Creates an Azure Key Vault and stores secrets for pipeline use
#

param(
    [string]$KeyVaultName = ""
)

$ErrorActionPreference = "Stop"

# ─── Configuration ────────────────────────────────────────────────────────────
$AppName     = "CostManagement-Fabric-SPN"
$Role        = "Cost Management Reader"
$EnvFile     = Join-Path $PSScriptRoot ".env"
$SecretYears = 2

# ─── Helper functions ─────────────────────────────────────────────────────────
function Write-Info  { param([string]$Message) Write-Host "[INFO] $Message" -ForegroundColor Green }
function Write-Warn  { param([string]$Message) Write-Host "[WARN] $Message" -ForegroundColor Yellow }
function Write-Err   { param([string]$Message) Write-Host "[ERROR] $Message" -ForegroundColor Red }

# ─── Pre-flight checks ───────────────────────────────────────────────────────
$azCmd = Get-Command az -ErrorAction SilentlyContinue
if (-not $azCmd) {
    Write-Err "Azure CLI (az) is not installed. Install from https://aka.ms/install-azure-cli"
    exit 1
}

try {
    $null = az account show 2>$null
    if ($LASTEXITCODE -ne 0) { throw "not logged in" }
} catch {
    Write-Err "Not logged in to Azure CLI. Run 'az login' first."
    exit 1
}

Write-Info "Azure CLI is installed and authenticated."

# ─── Get current subscription info ───────────────────────────────────────────
$accountJson = az account show -o json | ConvertFrom-Json
$SubscriptionId   = $accountJson.id
$SubscriptionName = $accountJson.name
$TenantId         = $accountJson.tenantId

Write-Info "Current subscription: $SubscriptionName ($SubscriptionId)"
Write-Info "Tenant ID: $TenantId"

# ─── Step 1: Create .env file if it doesn't exist ────────────────────────────
if (-not (Test-Path $EnvFile)) {
    Write-Info "Creating $EnvFile file..."
    $timestamp = (Get-Date).ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:ssZ")
    @"
# Azure Cost Management API Configuration
# Auto-generated by GetKeys.ps1 on $timestamp

# Azure Subscription
AZURE_SUBSCRIPTION_ID=
AZURE_SUBSCRIPTION_NAME=

# Azure Tenant
AZURE_TENANT_ID=

# Service Principal credentials
AZURE_CLIENT_ID=
AZURE_CLIENT_SECRET=

# Service Principal display name (for reference)
AZURE_SPN_NAME=

# Ontology display name (optional)
ONTOLOGY_DISPLAY_NAME=CostManagementOntology

# Cost data lookback (number of days to fetch/refresh, default 7)
COST_LOOKBACK_DAYS=7

# Azure Key Vault (for pipeline auth - set by GetKeys.ps1 -KeyVaultName)
# When set, notebooks pull secrets from Key Vault instead of .env
KEY_VAULT_URL=

# Fabric Lakehouse connection (used by UploadDashboard.ps1)
# Find your SQL endpoint: Fabric Portal -> Lakehouse -> Settings -> SQL analytics endpoint -> Server
LAKEHOUSE_SQL_ENDPOINT=
LAKEHOUSE_DATABASE=CostManagementLakehouse
"@ | Set-Content -Path $EnvFile -Encoding UTF8
    Write-Info "$EnvFile created."
} else {
    Write-Info "$EnvFile already exists."
}

# ─── Step 2: Check if Service Principal already exists ────────────────────────
Write-Info "Checking for existing service principal '$AppName'..."

$existingApps = az ad app list --display-name $AppName -o json 2>$null | ConvertFrom-Json
$ClientId     = $null
$ClientSecret = $null

if ($existingApps -and $existingApps.Count -gt 0) {
    $ClientId = $existingApps[0].appId
    Write-Info "Service principal '$AppName' already exists (Client ID: $ClientId)."

    Write-Warn "Creating a new client secret (old secrets are not retrievable)..."
    $credJson = az ad app credential reset --id $ClientId --years $SecretYears -o json | ConvertFrom-Json
    $ClientSecret = $credJson.password

    if (-not $ClientSecret) {
        Write-Err "Failed to parse client secret. Check manually."
        exit 1
    }
} else {
    # ─── Step 3: Create the Service Principal ─────────────────────────────────
    Write-Info "Creating service principal '$AppName'..."

    $spJson = az ad sp create-for-rbac --name $AppName --years $SecretYears -o json | ConvertFrom-Json
    $ClientId     = $spJson.appId
    $ClientSecret = $spJson.password

    if (-not $ClientId -or -not $ClientSecret) {
        Write-Err "Failed to parse service principal output. Check manually."
        exit 1
    }

    Write-Info "Service principal created: $ClientId"
}

# ─── Step 4: Assign Cost Management Reader role ──────────────────────────────
Write-Info "Checking role assignment for '$Role' on subscription..."

$scope = "/subscriptions/$SubscriptionId"
$existingRole = az role assignment list --assignee $ClientId --role $Role --scope $scope -o json 2>$null | ConvertFrom-Json

if ($existingRole -and $existingRole.Count -gt 0) {
    Write-Info "Role '$Role' is already assigned."
} else {
    Write-Info "Assigning '$Role' role on subscription $SubscriptionId..."
    az role assignment create --assignee $ClientId --role $Role --scope $scope --output none
    if ($LASTEXITCODE -ne 0) {
        Write-Err "Failed to assign role. You may need Owner or User Access Administrator permissions."
        exit 1
    }
    Write-Info "Role assigned successfully."
}

# ─── Step 5: Update the .env file ────────────────────────────────────────────
Write-Info "Updating $EnvFile with credentials..."

$timestamp = (Get-Date).ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:ssZ")
@"
# Azure Cost Management API Configuration
# Auto-generated by GetKeys.ps1 on $timestamp
# WARNING: This file contains secrets. Do NOT commit to source control.

# Azure Subscription
AZURE_SUBSCRIPTION_ID=$SubscriptionId
AZURE_SUBSCRIPTION_NAME=$SubscriptionName

# Azure Tenant
AZURE_TENANT_ID=$TenantId

# Service Principal credentials
AZURE_CLIENT_ID=$ClientId
AZURE_CLIENT_SECRET=$ClientSecret

# Service Principal display name (for reference)
AZURE_SPN_NAME=$AppName

# Ontology display name (optional -- used by 03_create_cost_ontology notebook)
ONTOLOGY_DISPLAY_NAME=CostManagementOntology

# Azure Key Vault (for pipeline auth - set by GetKeys.ps1 -KeyVaultName)
# When set, notebooks pull secrets from Key Vault instead of .env
KEY_VAULT_URL=

# Fabric Lakehouse connection (used by UploadDashboard.ps1)
# Find your SQL endpoint: Fabric Portal -> Lakehouse -> Settings -> SQL analytics endpoint -> Server
LAKEHOUSE_SQL_ENDPOINT=
LAKEHOUSE_DATABASE=CostManagementLakehouse
"@ | Set-Content -Path $EnvFile -Encoding UTF8

Write-Info "$EnvFile updated successfully."

# ─── Summary ─────────────────────────────────────────────────────────────────
$secretPreview = $ClientSecret.Substring(0, [Math]::Min(8, $ClientSecret.Length)) + "********************************"

Write-Host ""
Write-Host "════════════════════════════════════════════════════════════════" -ForegroundColor Cyan
Write-Host "  Setup Complete" -ForegroundColor Cyan
Write-Host "════════════════════════════════════════════════════════════════" -ForegroundColor Cyan
Write-Host ""
Write-Host "  Subscription:    $SubscriptionName"
Write-Host "  Subscription ID: $SubscriptionId"
Write-Host "  Tenant ID:       $TenantId"
Write-Host "  SPN Name:        $AppName"
Write-Host "  Client ID:       $ClientId"
Write-Host "  Client Secret:   $secretPreview"
Write-Host "  Role:            $Role"
Write-Host "  .env File:       $EnvFile"
Write-Host ""
Write-Host "  Next steps:"
Write-Host "    1. Upload notebooks to your Fabric workspace"
Write-Host "    2. Upload .env to Lakehouse Files (or set env vars)"
Write-Host "    3. Run 01_download_cost_data.ipynb"
Write-Host "    4. Run 03_create_cost_ontology.ipynb"
Write-Host ""
Write-Host "════════════════════════════════════════════════════════════════" -ForegroundColor Cyan

# ─── Step 6 (Optional): Create Key Vault and store secrets ───────────────────
if ($KeyVaultName) {
    Write-Host ""
    Write-Info "Setting up Azure Key Vault: $KeyVaultName"

    # Get resource group for Key Vault (use the subscription's default location)
    $kvResourceGroup = "rg-cost-management-keys"
    $kvLocation = "eastus"

    # Create resource group if it doesn't exist
    $rgExists = $null
    try { $rgExists = az group show --name $kvResourceGroup -o json 2>$null | ConvertFrom-Json } catch {}
    if (-not $rgExists) {
        Write-Info "Creating resource group: $kvResourceGroup"
        az group create --name $kvResourceGroup --location $kvLocation --output none
    }

    # Create Key Vault if it doesn't exist
    $kvExists = $null
    try { $kvExists = az keyvault show --name $KeyVaultName -o json 2>$null | ConvertFrom-Json } catch {}
    if (-not $kvExists) {
        Write-Info "Creating Key Vault: $KeyVaultName"
        az keyvault create `
            --name $KeyVaultName `
            --resource-group $kvResourceGroup `
            --location $kvLocation `
            --enable-rbac-authorization false `
            --output none
    } else {
        Write-Info "Key Vault '$KeyVaultName' already exists."
    }

    # Store secrets
    Write-Info "Storing secrets in Key Vault..."
    az keyvault secret set --vault-name $KeyVaultName --name "AZURE-TENANT-ID" --value $TenantId --output none
    az keyvault secret set --vault-name $KeyVaultName --name "AZURE-CLIENT-ID" --value $ClientId --output none
    az keyvault secret set --vault-name $KeyVaultName --name "AZURE-CLIENT-SECRET" --value $ClientSecret --output none
    az keyvault secret set --vault-name $KeyVaultName --name "AZURE-SUBSCRIPTION-ID" --value $SubscriptionId --output none

    $kvUrl = "https://$KeyVaultName.vault.azure.net/"
    Write-Info "Secrets stored. Key Vault URL: $kvUrl"

    # Update .env with Key Vault URL
    $envContent = Get-Content $EnvFile -Raw
    if ($envContent -match 'KEY_VAULT_URL=') {
        $envContent = $envContent -replace 'KEY_VAULT_URL=.*', "KEY_VAULT_URL=$kvUrl"
        [System.IO.File]::WriteAllText($EnvFile, $envContent)
    } else {
        Add-Content $EnvFile "`nKEY_VAULT_URL=$kvUrl"
    }
    Write-Info "KEY_VAULT_URL written to .env"

    Write-Host ""
    Write-Host "  Key Vault:   $kvUrl" -ForegroundColor Green
    Write-Host "  Secrets:     AZURE-TENANT-ID, AZURE-CLIENT-ID, AZURE-CLIENT-SECRET, AZURE-SUBSCRIPTION-ID" -ForegroundColor Green
    Write-Host ""
    Write-Host "  Pipeline setup:" -ForegroundColor Yellow
    Write-Host "    1. Create a workspace identity: Workspace Settings > Workspace identity > + Workspace identity"
    Write-Host "    2. Grant the workspace identity 'Key Vault Secrets User' role on the vault"
    Write-Host "    3. Upload .env to Lakehouse Files (KEY_VAULT_URL is set)"
    Write-Host "    4. Notebooks will auto-detect Key Vault and pull secrets at runtime"
    Write-Host ""
}
