{
  "compatibilityLevel": 1604,
  "model": {
    "annotations": [
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"subscription\",\"resource_group\",\"resource\",\"cost_record\",\"meter_category\",\"service\",\"Lakehouse SQL Endpoint\",\"Lakehouse Database\"]"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "expressions": [
      {
        "name": "Lakehouse SQL Endpoint",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Text"
          }
        ],
        "expression": "\"fw3a7dnuunnujpowpfko6lfyc4-enh443b3srkexk2pzltnaqnnaa.datawarehouse.fabric.microsoft.com\" meta [IsParameterQuery=true, Type=\"Text\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "e1000001-0000-4000-a000-000000000001"
      },
      {
        "name": "Lakehouse Database",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Text"
          }
        ],
        "expression": "\"dbAzureCostLakeHouse\" meta [IsParameterQuery=true, Type=\"Text\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "e1000002-0000-4000-a000-000000000002"
      }
    ],
    "relationships": [
      {
        "name": "subscription_to_resource_group",
        "fromColumn": "subscriptionId",
        "fromTable": "resource_group",
        "toColumn": "subscriptionId",
        "toTable": "subscription"
      },
      {
        "name": "resource_group_to_resource",
        "fromColumn": "resourceGroupId",
        "fromTable": "resource",
        "toColumn": "resourceGroupId",
        "toTable": "resource_group"
      },
      {
        "name": "resource_to_cost_record",
        "fromColumn": "resourceId",
        "fromTable": "cost_record",
        "toColumn": "resourceId",
        "toTable": "resource"
      },
      {
        "name": "meter_to_cost_record",
        "fromColumn": "meterId",
        "fromTable": "cost_record",
        "toColumn": "meterId",
        "toTable": "meter_category"
      },
      {
        "name": "service_to_cost_record",
        "fromColumn": "serviceId",
        "fromTable": "cost_record",
        "toColumn": "serviceId",
        "toTable": "service"
      }
    ],
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "subscription",
        "columns": [
          {
            "name": "subscriptionId",
            "dataType": "string",
            "lineageTag": "c1100001-0000-4000-a000-000000000001",
            "sourceColumn": "subscriptionId",
            "summarizeBy": "none"
          },
          {
            "name": "subscriptionName",
            "dataType": "string",
            "lineageTag": "c1100002-0000-4000-a000-000000000002",
            "sourceColumn": "subscriptionName",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "t1000001-0000-4000-a000-000000000001",
        "partitions": [
          {
            "name": "subscription",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(#\"Lakehouse SQL Endpoint\", #\"Lakehouse Database\"),",
                "    data = Source{[Schema=\"dbo\",Item=\"subscription\"]}[Data],",
                "    SafeLower = (x) => if x = null then null else Text.Lower(x),",
                "    Lower = Table.TransformColumns(data, {{\"subscriptionId\", SafeLower, type text}}),",
                "    Grouped = Table.Group(Lower, {\"subscriptionId\"}, {{\"subscriptionName\", each List.Max([subscriptionName]), type text}})",
                "in",
                "    Grouped"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "resource_group",
        "columns": [
          {
            "name": "resourceGroupId",
            "dataType": "string",
            "lineageTag": "c2100001-0000-4000-a000-000000000001",
            "sourceColumn": "resourceGroupId",
            "summarizeBy": "none"
          },
          {
            "name": "resourceGroupName",
            "dataType": "string",
            "lineageTag": "c2100002-0000-4000-a000-000000000002",
            "sourceColumn": "resourceGroupName",
            "summarizeBy": "none"
          },
          {
            "name": "subscriptionId",
            "dataType": "string",
            "lineageTag": "c2100003-0000-4000-a000-000000000003",
            "sourceColumn": "subscriptionId",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "t2000001-0000-4000-a000-000000000001",
        "partitions": [
          {
            "name": "resource_group",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(#\"Lakehouse SQL Endpoint\", #\"Lakehouse Database\"),",
                "    data = Source{[Schema=\"dbo\",Item=\"resource_group\"]}[Data],",
                "    SafeLower = (x) => if x = null then null else Text.Lower(x),",
                "    Lower = Table.TransformColumns(data, {{\"resourceGroupId\", SafeLower, type text}, {\"subscriptionId\", SafeLower, type text}}),",
                "    Grouped = Table.Group(Lower, {\"resourceGroupId\"}, {{\"resourceGroupName\", each List.Max([resourceGroupName]), type text}, {\"subscriptionId\", each List.Max([subscriptionId]), type text}})",
                "in",
                "    Grouped"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "resource",
        "columns": [
          {
            "name": "resourceId",
            "dataType": "string",
            "lineageTag": "c3100001-0000-4000-a000-000000000001",
            "sourceColumn": "resourceId",
            "summarizeBy": "none"
          },
          {
            "name": "resourceType",
            "dataType": "string",
            "lineageTag": "c3100002-0000-4000-a000-000000000002",
            "sourceColumn": "resourceType",
            "summarizeBy": "none"
          },
          {
            "name": "resourceGroupName",
            "dataType": "string",
            "lineageTag": "c3100003-0000-4000-a000-000000000003",
            "sourceColumn": "resourceGroupName",
            "summarizeBy": "none"
          },
          {
            "name": "resourceGroupId",
            "dataType": "string",
            "lineageTag": "c3100004-0000-4000-a000-000000000004",
            "sourceColumn": "resourceGroupId",
            "summarizeBy": "none"
          },
          {
            "name": "location",
            "dataType": "string",
            "lineageTag": "c3100005-0000-4000-a000-000000000005",
            "sourceColumn": "location",
            "summarizeBy": "none"
          },
          {
            "name": "resourceName",
            "dataType": "string",
            "expression": "VAR rid = resource[resourceId] VAR slashCount = LEN(rid) - LEN(SUBSTITUTE(rid, \"/\", \"\")) RETURN IF(slashCount > 0, MID(rid, FIND(UNICHAR(167), SUBSTITUTE(rid, \"/\", UNICHAR(167), slashCount)) + 1, LEN(rid)), rid)",
            "isDataTypeInferred": true,
            "lineageTag": "c3100006-0000-4000-a000-000000000006",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "t3000001-0000-4000-a000-000000000001",
        "partitions": [
          {
            "name": "resource",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(#\"Lakehouse SQL Endpoint\", #\"Lakehouse Database\"),",
                "    data = Source{[Schema=\"dbo\",Item=\"resource\"]}[Data],",
                "    SafeLower = (x) => if x = null then null else Text.Lower(x),",
                "    Lower = Table.TransformColumns(data, {{\"resourceId\", SafeLower, type text}, {\"resourceGroupId\", SafeLower, type text}}),",
                "    Grouped = Table.Group(Lower, {\"resourceId\"}, {{\"resourceType\", each List.Max([resourceType]), type text}, {\"resourceGroupName\", each List.Max([resourceGroupName]), type text}, {\"resourceGroupId\", each List.Max([resourceGroupId]), type text}, {\"location\", each List.Max([location]), type text}})",
                "in",
                "    Grouped"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "cost_record",
        "columns": [
          {
            "name": "costRecordId",
            "dataType": "int64",
            "lineageTag": "c4100001-0000-4000-a000-000000000001",
            "sourceColumn": "costRecordId",
            "summarizeBy": "none"
          },
          {
            "name": "subscriptionId",
            "dataType": "string",
            "lineageTag": "c4100002-0000-4000-a000-000000000002",
            "sourceColumn": "subscriptionId",
            "summarizeBy": "none"
          },
          {
            "name": "resourceGroupId",
            "dataType": "string",
            "lineageTag": "c4100003-0000-4000-a000-000000000003",
            "sourceColumn": "resourceGroupId",
            "summarizeBy": "none"
          },
          {
            "name": "resourceId",
            "dataType": "string",
            "lineageTag": "c4100004-0000-4000-a000-000000000004",
            "sourceColumn": "resourceId",
            "summarizeBy": "none"
          },
          {
            "name": "meterId",
            "dataType": "string",
            "lineageTag": "c4100005-0000-4000-a000-000000000005",
            "sourceColumn": "meterId",
            "summarizeBy": "none"
          },
          {
            "name": "serviceId",
            "dataType": "string",
            "lineageTag": "c4100006-0000-4000-a000-000000000006",
            "sourceColumn": "serviceId",
            "summarizeBy": "none"
          },
          {
            "name": "usageDate",
            "annotations": [
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "c4100007-0000-4000-a000-000000000007",
            "sourceColumn": "usageDate",
            "summarizeBy": "none"
          },
          {
            "name": "preTaxCost",
            "dataType": "double",
            "formatString": "$#,##0.00",
            "lineageTag": "c4100008-0000-4000-a000-000000000008",
            "sourceColumn": "preTaxCost",
            "summarizeBy": "sum"
          },
          {
            "name": "quantity",
            "dataType": "double",
            "lineageTag": "c4100009-0000-4000-a000-000000000009",
            "sourceColumn": "quantity",
            "summarizeBy": "sum"
          },
          {
            "name": "unitOfMeasure",
            "dataType": "string",
            "lineageTag": "c4100010-0000-4000-a000-000000000010",
            "sourceColumn": "unitOfMeasure",
            "summarizeBy": "none"
          },
          {
            "name": "chargeType",
            "dataType": "string",
            "lineageTag": "c4100011-0000-4000-a000-000000000011",
            "sourceColumn": "chargeType",
            "summarizeBy": "none"
          },
          {
            "name": "location",
            "dataType": "string",
            "lineageTag": "c4100012-0000-4000-a000-000000000012",
            "sourceColumn": "location",
            "summarizeBy": "none"
          },
          {
            "name": "Currency",
            "dataType": "string",
            "lineageTag": "c4100013-0000-4000-a000-000000000013",
            "sourceColumn": "Currency",
            "summarizeBy": "none"
          },
          {
            "name": "usageMonth",
            "dataType": "string",
            "expression": "FORMAT(cost_record[usageDate], \"YYYY-MM\")",
            "isDataTypeInferred": true,
            "lineageTag": "c4100014-0000-4000-a000-000000000014",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "t4000001-0000-4000-a000-000000000001",
        "measures": [
          {
            "name": "Total Cost",
            "expression": "SUM(cost_record[preTaxCost])",
            "formatString": "$#,##0.00",
            "lineageTag": "m4100001-0000-4000-a000-000000000001"
          },
          {
            "name": "Forecast Cost",
            "description": "Simple forecast header value used by the Azure cost dashboard page.",
            "expression": "[Total Cost] * 1.0375",
            "formatString": "$#,##0.00",
            "lineageTag": "m4100002-0000-4000-a000-000000000002"
          },
          {
            "name": "Budget Display",
            "description": "Budget placeholder header value used by the Azure cost dashboard page.",
            "expression": "\"--\"",
            "lineageTag": "m4100003-0000-4000-a000-000000000003"
          }
        ],
        "partitions": [
          {
            "name": "cost_record",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(#\"Lakehouse SQL Endpoint\", #\"Lakehouse Database\"),",
                "    data = Source{[Schema=\"dbo\",Item=\"cost_record\"]}[Data],",
                "    SafeLower = (x) => if x = null then null else Text.Lower(x),",
                "    Lower = Table.TransformColumns(data, {{\"subscriptionId\", SafeLower, type text}, {\"resourceGroupId\", SafeLower, type text}, {\"resourceId\", SafeLower, type text}, {\"meterId\", SafeLower, type text}, {\"serviceId\", SafeLower, type text}})",
                "in",
                "    Lower"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "meter_category",
        "columns": [
          {
            "name": "meterId",
            "dataType": "string",
            "lineageTag": "c5100001-0000-4000-a000-000000000001",
            "sourceColumn": "meterId",
            "summarizeBy": "none"
          },
          {
            "name": "meterCategory",
            "dataType": "string",
            "lineageTag": "c5100002-0000-4000-a000-000000000002",
            "sourceColumn": "meterCategory",
            "summarizeBy": "none"
          },
          {
            "name": "meterSubCategory",
            "dataType": "string",
            "lineageTag": "c5100003-0000-4000-a000-000000000003",
            "sourceColumn": "meterSubCategory",
            "summarizeBy": "none"
          },
          {
            "name": "meterName",
            "dataType": "string",
            "lineageTag": "c5100004-0000-4000-a000-000000000004",
            "sourceColumn": "meterName",
            "summarizeBy": "none"
          },
          {
            "name": "unitOfMeasure",
            "dataType": "string",
            "lineageTag": "c5100005-0000-4000-a000-000000000005",
            "sourceColumn": "unitOfMeasure",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "t5000001-0000-4000-a000-000000000001",
        "partitions": [
          {
            "name": "meter_category",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(#\"Lakehouse SQL Endpoint\", #\"Lakehouse Database\"),",
                "    data = Source{[Schema=\"dbo\",Item=\"meter_category\"]}[Data],",
                "    SafeLower = (x) => if x = null then null else Text.Lower(x),",
                "    Lower = Table.TransformColumns(data, {{\"meterId\", SafeLower, type text}}),",
                "    Grouped = Table.Group(Lower, {\"meterId\"}, {{\"meterCategory\", each List.Max([meterCategory]), type text}, {\"meterSubCategory\", each List.Max([meterSubCategory]), type text}, {\"meterName\", each List.Max([meterName]), type text}, {\"unitOfMeasure\", each List.Max([unitOfMeasure]), type text}})",
                "in",
                "    Grouped"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "service",
        "columns": [
          {
            "name": "serviceId",
            "dataType": "string",
            "lineageTag": "c6100001-0000-4000-a000-000000000001",
            "sourceColumn": "serviceId",
            "summarizeBy": "none"
          },
          {
            "name": "serviceName",
            "dataType": "string",
            "lineageTag": "c6100002-0000-4000-a000-000000000002",
            "sourceColumn": "serviceName",
            "summarizeBy": "none"
          },
          {
            "name": "chargeType",
            "dataType": "string",
            "lineageTag": "c6100003-0000-4000-a000-000000000003",
            "sourceColumn": "chargeType",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "t6000001-0000-4000-a000-000000000001",
        "partitions": [
          {
            "name": "service",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(#\"Lakehouse SQL Endpoint\", #\"Lakehouse Database\"),",
                "    data = Source{[Schema=\"dbo\",Item=\"service\"]}[Data],",
                "    SafeLower = (x) => if x = null then null else Text.Lower(x),",
                "    Lower = Table.TransformColumns(data, {{\"serviceId\", SafeLower, type text}}),",
                "    Grouped = Table.Group(Lower, {\"serviceId\"}, {{\"serviceName\", each List.Max([serviceName]), type text}, {\"chargeType\", each List.Max([chargeType]), type text}})",
                "in",
                "    Grouped"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Group By",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "t7000001-0000-4000-a000-000000000001"
          },
          {
            "name": "ParameterMetadata",
            "value": "{\"version\":3,\"kind\":2}"
          }
        ],
        "columns": [
          {
            "name": "Value1",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "26a0741b-8460-4a3b-a0eb-a8c9c6d56fe1",
            "sourceColumn": "[Value1]",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Value2",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "57b12f3c-5ecc-449d-9a95-dbfd93577147",
            "sourceColumn": "[Value2]",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Value3",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "16022699-e6ed-4ed3-9400-34b2ff76d54d",
            "sourceColumn": "[Value3]",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "t7000001-0000-4000-a000-000000000001",
        "partitions": [
          {
            "name": "Group By",
            "mode": "import",
            "source": {
              "expression": [
                "{",
                "    (\"Resource\", NAMEOF('resource'[resourceName]), 0),",
                "    (\"Resource Group\", NAMEOF('resource_group'[resourceGroupName]), 1),",
                "    (\"Meter Category\", NAMEOF('meter_category'[meterCategory]), 2),",
                "    (\"Service\", NAMEOF('service'[serviceName]), 3)",
                "}"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Granularity",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "t8000001-0000-4000-a000-000000000001"
          },
          {
            "name": "ParameterMetadata",
            "value": "{\"version\":3,\"kind\":2}"
          }
        ],
        "columns": [
          {
            "name": "Value1",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "c38da1f1-54f4-4702-aaaa-2b94113a5b05",
            "sourceColumn": "[Value1]",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Value2",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "9a8d5d92-731c-4484-b07d-2c6ec556a081",
            "sourceColumn": "[Value2]",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Value3",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "e9977c3b-aea5-46d9-b929-82c47dd33cc6",
            "sourceColumn": "[Value3]",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "t8000001-0000-4000-a000-000000000001",
        "partitions": [
          {
            "name": "Granularity",
            "mode": "import",
            "source": {
              "expression": [
                "{",
                "    (\"Daily\", NAMEOF('cost_record'[usageDate]), 0),",
                "    (\"Monthly\", NAMEOF('cost_record'[usageMonth]), 1)",
                "}"
              ],
              "type": "calculated"
            }
          }
        ]
      }
    ]
  }
}